# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: setup-chromedriver
      uses: nanasess/setup-chromedriver@master
    - name: unzip chromedriver
      run: unzip chromedriver_linux64.zip && \
           chown root:root /usr/bin/chromedriver && \
           chmod +x /usr/bin/chromedriver
    - name: install google chrome
      run: wget -q https://script.install.devinsideyou.com/google-chrome
    - name: change permission to google chrome
      run: sudo chmod +x google-chrome && ./google-chrome
    - name: Build with Maven
      run: mvn clean verify -Denvironment=staging -Dtags=@defaultMode --file pom.xml
